Refactor/enrich the tests of the analysis part of modules
quark-engine/quark-engine pull request #182
Opened 2021-06-17 07:32 UTC by haeter525

### Title: Refactor/enrich the tests of the analysis part of modules
#### Description
Please refer to [here](https://github.com/quark-engine/gsoc2021-ShengFengLu/issues/1). I want to write tests to increase the test coverage for Quark. This is the first PR.

In this PR, I focus on these files.

1. quark.py
2. apkinfo.py
2. pyeval.py
3. registerobject.py
4. tableobject.py

#### Why are these files first?

1. A [risk assessment](https://github.com/quark-engine/quark-engine/discussions/173#discussioncomment-831656) shows that those files have the highest priorities to write tests.
2. Those files compose the Dalvik bytecode loader and the well-known five-stage analysis in Quark.
3. The upcoming replacement of Androguard mainly makes changes to those files.

#### Code Changes
+ **For the existing tests**: Divide them by their test scenarios.
+ **For the new tests**: Add them according to two strategies and the coding guideline discussed in the above issue.

| Files                    | # Tests added for normal inputs | # Tests added for error inputs| # Tests modified |
| ------------------------ | :-----------------------------: | :--------------------------------: | :--------------: |
| `test_pyeval.py`         |                9                |                 5                 |        5         |
| `test_quark.py`          |                3                |                 8                  |        5         |
| `test_tableobject.py`    |                3                |                 3                  |        4         |
| `test_apkinfo.py` |                1                |                2                  |        1         |
| `test_registerobject.py` |                3                |                 3                  |        -         |
| `test_registerobject.py` |                3                |                 3                  |        -         |

**Note**
I found a strangle behavior in `_invoke()` at `pyeval.py`. No matter the invoked function gives a return value or not, it changes the value of the return register `ret_stack`.

#### Related Discussion
1. Issue [https://github.com/quark-engine/gsoc2021-ShengFengLu/issues/1](https://github.com/quark-engine/gsoc2021-ShengFengLu/issues/1)
2. Discussion [https://github.com/quark-engine/quark-engine/discussions/173](https://github.com/quark-engine/quark-engine/discussions/173)

2021-06-17 07:32 UTC, pep8speaks commented
Hello @haeter525! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`tests/Evaluator/test_pyeval.py`](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Evaluator/test_pyeval.py):

> [Line 89:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Evaluator/test_pyeval.py#L89): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 93:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Evaluator/test_pyeval.py#L93): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 96:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Evaluator/test_pyeval.py#L96): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 119:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Evaluator/test_pyeval.py#L119): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 175:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Evaluator/test_pyeval.py#L175): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 343:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Evaluator/test_pyeval.py#L343): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 354:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Evaluator/test_pyeval.py#L354): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)

* In the file [`tests/Object/test_apkinfo.py`](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_apkinfo.py):

> [Line 37:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_apkinfo.py#L37): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

* In the file [`tests/Object/test_quark.py`](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py):

> [Line 74:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py#L74): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 79:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py#L79): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 95:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py#L95): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 104:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py#L104): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 131:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py#L131): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 155:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py#L155): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 171:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py#L171): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 253:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py#L253): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 275:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py#L275): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 283:80](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py#L283): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 284:13](https://github.com/quark-engine/quark-engine/blob/9d4022fb631aa11efcc6caf33d9925c6bf5b8314/tests/Object/test_quark.py#L284): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'

2021-06-18 07:11 UTC, krnick requested changes
Nice work! 👍 
Thank you @haeter525 for enriching Quark's testing of this part. It is really helpful for the stability of Quark.
I left some comments on this PR, which are some trivial errors that could be fixed quickly.

2021-06-24 07:28 UTC, haeter525 commented on tests/Object/test_tableobject.py
> +    def test_insert_with_num_beyond_max(self, table_obj):
Its objective is to test the function runs without side effects.
But since it is confusing, I have added more code to it.

2021-06-24 07:28 UTC, haeter525 commented on tests/Object/test_registerobject.py
> +        assert list(standard_register_obj.called_by_func)[-1] == value
Fixed. Thank you.

2021-06-24 07:28 UTC, haeter525 commented on tests/Object/test_apkinfo.py
> +from posixpath import basename
Fixed. Thank you.

2021-06-24 07:28 UTC, haeter525 commented on tests/Object/test_apkinfo.py
> +        filepath = "UNEXIST_FILE"
Fixed. Thank you.

2021-06-24 07:28 UTC, haeter525 commented on tests/Evaluator/test_pyeval.py
> +    @pytest.mark.skip(reasopytn="discussion needed.")
Oops, it was a typo. Fixed.

2021-06-24 07:35 UTC, haeter525 commented
Hi, @krnick 

I have fixed the errors you mentioned and checked the rest of the code carefully. Please take a look. Thank you :)

2021-06-24 07:42 UTC, krnick approved these changes
LGTM, thank you @haeter525 for the patch!

2021-06-24 07:44 UTC, merged