Parallelize the analysis
quark-engine/quark-engine pull request #223
Opened 2021-07-29 02:45 UTC by haeter525

**Description**

This PR adds a rule-based parallelization feature to Quark analysis. It allows Quark to scan multiple rules at a time.

**Usage**

Add the option `-j` to set the number of processes that Quark can use for analysis.
(Default is 1, to disable this feature.)

```
quark -a PATH_TO_APK -s -j NUMBER_OF_RULES
```

**Code changes**

+ `quark/cli.py`
  + Add the option `-j` as mentioned above.
  + Parallelly start the analysis of each rule before Quark askes the results.
+ `quark/parallelquark.py`
  + A subclass of Quark that handles the parallelization work.

2021-07-29 02:45 UTC, pep8speaks commented
Hello @haeter525! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`quark/cli.py`](https://github.com/quark-engine/quark-engine/blob/3cf9a37579a6390b880b4ccd8fd199231a223541/quark/cli.py):

> [Line 151:80](https://github.com/quark-engine/quark-engine/blob/3cf9a37579a6390b880b4ccd8fd199231a223541/quark/cli.py#L151): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 185:80](https://github.com/quark-engine/quark-engine/blob/3cf9a37579a6390b880b4ccd8fd199231a223541/quark/cli.py#L185): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 191:80](https://github.com/quark-engine/quark-engine/blob/3cf9a37579a6390b880b4ccd8fd199231a223541/quark/cli.py#L191): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 245:80](https://github.com/quark-engine/quark-engine/blob/3cf9a37579a6390b880b4ccd8fd199231a223541/quark/cli.py#L245): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 332:80](https://github.com/quark-engine/quark-engine/blob/3cf9a37579a6390b880b4ccd8fd199231a223541/quark/cli.py#L332): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

* In the file [`quark/core/parallelquark.py`](https://github.com/quark-engine/quark-engine/blob/3cf9a37579a6390b880b4ccd8fd199231a223541/quark/core/parallelquark.py):

> [Line 28:80](https://github.com/quark-engine/quark-engine/blob/3cf9a37579a6390b880b4ccd8fd199231a223541/quark/core/parallelquark.py#L28): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 90:80](https://github.com/quark-engine/quark-engine/blob/3cf9a37579a6390b880b4ccd8fd199231a223541/quark/core/parallelquark.py#L90): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2021-08-04 03:00 UTC, krnick requested changes
Thank you @haeter525 for this patch, I have left some comments for you. I believe Quark can process faster through parallel processing.

By the way, have you ever calculated the average time for parallelization? How much time can parallelization improve?

2021-08-17 03:59 UTC, haeter525 commented on quark/cli.py
> +                if len(
Thank you for pointing out this issue.
I will fix it!

2021-08-17 04:00 UTC, haeter525 commented on README.md
> +### Parallelize the analysis
Thank you for the suggestion!

2021-08-17 06:51 UTC, merged