[Quark#446] Add quark script case for CWE-295
quark-engine/quark-engine pull request #447
Opened 2022-12-30 11:56 UTC by PoJenC

## Description
This PR aims to close Issue https://github.com/quark-engine/quark-script/issues/446

## File Changes
Modify  quark/script/\_\_init\_\_.py

2023-01-03 23:23 UTC, sidra-asa commented
@PoJenC

Thank you for contributing to the CWE-295 showcase.
Here are my suggestions.

1. the last descriptor in the API Spec should be RETURN.
2. In the script, the descriptor of OVERRIDE_METHOD seems to be incorrect in the script.
3. Please submit at least one test case related to the newly added findSuperclassHierarchy method.

2023-01-04 04:12 UTC, PoJenC commented
@sidra-asa 
Thanks for your patience in reviewing so in detail. I've corrected those issues that you mentioned in my last commit. Please help to check whether it's okay for Quark or not.
Thanks again.

2023-01-05 17:02 UTC, sidra-asa commented
@PoJenC 

Thanks for the newly commits, the test case looks good.
But I have some suggestions for Quark Script API findSuperclassHierarchy method.

1. it is better to use `list()` to initialize an empty list instance.

2. `targetClass` is not a keyword in python. So for the sake of code readability, it is fine to use targetClass.

Also, I have an additional suggestion for Quark scripts.
The comment style of the variables in `TARGET_METHOD` and `OVERRIDE_METHOD` don't seem to be consistent.
Can you change the annotation of descriptors in `OVERRIDE_METHOD` to Inline annotation style?

By the way, some comments are not aligned.
Can you change them as well?
I think removing a space in the comment for the class name in `TARGET_METHOD` would be fine.

2023-01-10 07:36 UTC, sidra-asa commented on quark/script/__init__.py
> -               ) for matchedMethod in matchedMethods]
They seem like irrelevant changes.

2023-01-11 07:45 UTC, sidra-asa approved these changes
LGTM.

@PoJenC  
Great work. Thank you.

2023-01-11 11:07 UTC, haeter525 commented
Hi @PoJenC. The last commit (79f2479919bbdd2902801f12690136707a2a32ad) accidentally adds back the third problem pointed out by @sidra-asa in the [comment](https://github.com/quark-engine/quark-engine/pull/447#issuecomment-1372482988). Could you fix it? Thanks.

2023-01-11 11:58 UTC, haeter525 requested changes
Additionally, please update the PR description accordingly. Thanks,

2023-01-11 11:58 UTC, haeter525 commented on docs/source/quark_script.rst
> +        "onReceivedSslError",              # method name
The comments here are not aligned. Please fix that.

2023-01-11 11:58 UTC, haeter525 commented on docs/source/quark_script.rst
> +        "(Landroid/webkit/WebView; Landroid/webkit/SslErrorHandler; Landroid/net/http/SslError;)V"
I suggest putting this comment at the end of line 1406. This way, the comment style used for this line is consistent with the above lines.

2023-01-11 13:14 UTC, PoJenC commented
@haeter525 Hi,
All annotation issues are updated(with the latest CWE-295 Quark Script).

2023-01-11 13:20 UTC, haeter525 requested changes

2023-01-11 13:20 UTC, haeter525 commented on docs/source/quark_script.rst
> +        print(f"CWE-295 is detected in method, {sslProceedCaller.fullName}")
Hi @PoJenC . According to [the reStructuredText spec.](https://docutils.sourceforge.io/docs/ref/rst/directives.html#admonitions), each line in the code block should start with four spaces. For example, line 1394 should be formatted as follows -
```
    from quark.script import findMethodInAPK
```

2023-01-11 13:44 UTC, haeter525 commented on docs/source/quark_script.rst
> +the method’s caller class.
The paragraph contains two typos ("A" and "\`\`\\"). Please fix them.

2023-01-11 13:51 UTC, haeter525 commented on docs/source/quark_script.rst
> +- **return**: Python list contains all superclas’s name of the this method.
The apostrophe in "superclas's" should be placed at the end of the word rather than the second-last letter.

2023-01-11 14:34 UTC, haeter525 commented on docs/source/quark_script.rst
> +==============================
According to [the reStructuredText spec.](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#sections), the underline of the title should be as long as the title.

For example,
```
methodInstance.findSuperclassHierarchy(none)
=========================================
```

2023-01-11 14:38 UTC, haeter525 commented on docs/source/quark_script.rst
>      CWE-328 is detected in ./ovaa.apk,
Please do not make irrelevant changes here.

2023-01-11 15:21 UTC, sidra-asa commented on docs/source/quark_script.rst
> +``MethodInstance.findSuperclassHierarchy``\ to get the supclass list of
The "supclass" means superclass ? It seems like a typo.

2023-01-11 15:57 UTC, haeter525 approved these changes
LGTM. @haeter525 approves this PR! Thank @PoJenC

2023-01-11 17:24 UTC, sidra-asa approved these changes
LGTM.

2023-01-12 01:28 UTC, merged