Add quark script to detect cwe 489
quark-engine/quark-engine pull request #458
Opened 2023-01-17 16:16 UTC by zinwang

# Detect CWE-489 in Android Application (allsafe.apk, AndroGoat.apk, pivaa.apk)

This scenario seeks to find **active debug code** in the APK file. See [CWE-489](https://cwe.mitre.org/data/definitions/489.html) for more details.

Let's use [allsafe.apk](https://github.com/t0thkr1s/allsafe), [AndroGoat.apk](https://github.com/satishpatnayak/AndroGoat), [pivaa.apk](https://github.com/HTBridge/pivaa) and the above APIs to show how Quark script find this vulnerability.

First, we use Quark API `getApplication` to get the application data in the manifest. Then we use `applicationInstance.isDebuggable` to check if the application sets the attribute `android:debuggable=true`. If **Yes**, that causes CWE-489 vulnerabilities.

## API Spec

### getApplication(samplePath)

- Description: Get the application from the manifest of the target sample.
- params: 
    1. `samplePath` : the file path of the target sample
- return: Application instance of the sample

### applicationInstance.isDebuggable(none)

- Description: Check if the application sets `android:debuggable=true`.
- params: none
- return:  True/False

### Quark Script CWE-328.py
```python
from quark.script import getApplication

SAMPLE_PATH = "allsafe.apk"

if getApplication(SAMPLE_PATH).isDebuggable():
    print(f"CWE-489 is detected in the {SAMPLE_PATH}")
```

### Quark Script Result
- **allsafe.apk**
```TEXT
$ python3 CWE-489.py
CWE-489 is detected in the allsafe.apk
```
- **AndroGoat.apk**
```TEXT
$ python3 CWE-489.py
CWE-489 is detected in the AndroGoat.apk
```
- **pivaa.apk**
```TEXT
$ python3 CWE-489.py
CWE-489 is detected in the pivaa.apk
```

2023-01-17 19:20 UTC, haeter525 commented on docs/source/quark_script.rst
> +- **return**: Application instance of the sample
Please make sure the PR description consistent with the doc.

2023-01-17 19:23 UTC, haeter525 commented on quark/script/__init__.py
> +    """
Please update the docstring here.

2023-01-17 19:26 UTC, haeter525 commented on docs/source/quark_script.rst
> +- **Description**: Check if the application sets ``android:debuggable=true``.
Please ensure the description here consistent with the docstring.

2023-01-17 19:48 UTC, haeter525 commented on docs/source/quark_script.rst
> +        print(f"CWE-489 is detected in the {SAMPLE_PATH}")
The sentence is not grammatically correct. The article, the, should not be put in front of a proper noun.

2023-01-17 19:56 UTC, haeter525 commented on docs/source/quark_script.rst
> +==========================
According to [the reStructuredText spec.](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#sections), the underline should be as long as the title.

2023-01-17 20:17 UTC, haeter525 commented on docs/source/quark_script.rst
> +Let's use `allsafe.apk <https://github.com/t0thkr1s/allsafe>`_, `AndroGoat.apk <https://github.com/satishpatnayak/AndroGoat>`_, `pivaa.apk <https://github.com/HTBridge/pivaa>`_ and the above APIs to
1. There is a missing comma in front of `and`.
2. Please fix the grammatical issue by adding the article `the` in front of `Quark Script`.
3. The word `find` should be `finds`

2023-01-17 20:21 UTC, haeter525 commented on quark/core/apkinfo.py
> +    def application(self) -> XMLElement:
Please add a docstring for this method as well.

2023-01-18 06:33 UTC, haeter525 commented on docs/source/quark_script.rst
> +First, we use Quark API ``getApplication`` to get the application data in the manifest. Then we use ``applicationInstance.isDebuggable`` to check if the application sets the attribute ``android:debug
I suggest change
"sets the attribute `android:debuggable=true`"
to
"sets the attribute `android:debuggable` to true"
cause the latter is more precise.

2023-01-18 06:47 UTC, haeter525 commented on docs/source/quark_script.rst
> +    1. ``samplePath`` : the file path of the target sample
Please remove the backticks here.

2023-01-18 10:11 UTC, haeter525 requested changes

2023-01-18 10:37 UTC, haeter525 commented
Thanks, @zinwang. I have no further comment.
@pulorsok, could you help review the document? Thanks.

2023-01-18 10:38 UTC, haeter525 approved these changes

2023-01-18 11:14 UTC, pulorsok commented
LGTM! @haeter525 please proceed!

2023-01-18 11:14 UTC, pulorsok approved these changes

2023-01-18 11:16 UTC, merged