Introducing the Quark Agent Web Interface
quark-engine/quark-engine pull request #678
Opened 2024-08-29 02:34 UTC by pulorsok

# Quark Agent - Your AI Assistant for Vulnerability Analysis

Quark Agent is an AI assistant from the Quark team, providing an easy and intuitive experience of vulnerability analysis. Acting like a real-life assistant, Quark Agent helps you focus on the vulnerability detection process and takes care of the rest.

With Quark Agent, you can perform analyses using only natural language. It creates Quark Script code following your ideas and adjusts the code promptly as you provide feedback.

# Showcase: Detecting CWE-798 with Quark Agent

Here’s a demonstration of using Quark Agent to detect the CWE-798 vulnerability in the ovaa.apk file.

### Step 1: Environments Requirements

*   Quark Agent requires Python 3.8 or above.

### Step 2: Install Quark Agent

*   Install Quark Agent by running:

```bash
git clone https://github.com/quark-engine/quark-engine.git & cd quark-engine
pip install .[QuarkAgent]
```

### Step 3: Prepare the Detection Rule and the Sample File

```bash
.
├── ...
├── quark                   
    ├── ...           
    ├── agent               # Put rule file and sample file here
    ├── ...                
```

### Step 4: Add your OpenAI API key

Add your OpenAI API key in `quarkAgentWeb.py`

```python
os.environ["OPENAI_API_KEY"] = 'your-api-key-here'
```

### Step 5: Run Quark Agent

```bash
$ python3 quark/agent/quarkAgentWeb.py

# You can now chat with Quark Agent in your browser. 
# The default URL is http://127.0.0.1:5000
```

Open a browser and navigate to `127.0.0.1:5000` to start using Quark Agent, as shown below.

![截圖 2024-08-28 晚上11.00.27](https://hackmd.io/_uploads/By6ggTni0.png)

# Future Plan

In the future, Quark Agent will visualize the vulnerability detection process as a flowchart, allowing users to easily design and edit detection workflows through the flowchart. Stay tuned!

2024-08-29 02:34 UTC, pep8speaks commented
Hello @pulorsok! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`quark/agent/quarkAgentWeb.py`](https://github.com/quark-engine/quark-engine/blob/fc186c49d04e303bc5c568d0d3605b9e43924ae2/quark/agent/quarkAgentWeb.py):

> [Line 11:80](https://github.com/quark-engine/quark-engine/blob/fc186c49d04e303bc5c568d0d3605b9e43924ae2/quark/agent/quarkAgentWeb.py#L11): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

2024-08-31 00:53 UTC, 18z commented
# Quark Agent - Your AI-powered Android APK Analyst

![quark agent demo](https://hackmd.io/_uploads/By6ggTni0.png)

With Quark Agent, you can perform analyses using only natural language. It creates Quark Script code following your ideas and adjusts the code promptly as you provide feedback.

# Showcase:

Here’s a demonstration of using Quark Agent to detect the CWE-798 vulnerability in the ovaa.apk file.

### Step 1: Environments Requirements

*   Make sure your  Python version is 3.8 or above.

### Step 2: Install Quark Agent

*   Install Quark Agent by running:

```bash
git clone https://github.com/quark-engine/quark-engine.git & cd quark-engine
pip install .[QuarkAgent]
```

### Step 3: Prepare the Detection Rule and the Sample File

```bash
.
├── ...
├── quark                   
    ├── ...           
    ├── agent               # Put rule file and sample file here
    ├── ...                
```

### Step 4: Add your OpenAI API key

Add your OpenAI API key in `quarkAgentWeb.py`

```python
os.environ["OPENAI_API_KEY"] = 'your-api-key-here'
```

### Step 5: Run Quark Agent

```bash
$ python3 quark/agent/quarkAgentWeb.py

# You can now chat with Quark Agent in your browser. 
# The default URL is http://127.0.0.1:5000
```

Open a browser and navigate to `127.0.0.1:5000` to start using Quark Agent

2024-08-31 02:15 UTC, haeter525 requested changes

2024-08-31 02:15 UTC, haeter525 commented on README.md
> +git clone https://github.com/quark-engine/quark-engine.git & cd quark-engine
The `&` in the command should be `&&`.

2024-08-31 02:15 UTC, haeter525 commented on README.md
> +*   Make sure your  Python version is 3.8 or above.
There is a extra space between `your` and `Python`.

2024-08-31 02:51 UTC, haeter525 approved these changes
LGTM. Thank @pulorsok.

2024-08-31 02:51 UTC, merged